### PR TITLE
Fix anonymous burmeister io

### PR DESCRIPTION
**Pull request by maximilian-felde**
fixed anonymous-burmeister write to file function

### CODE REVIEW

**Comment by tomhanika** [comment]
Dear maximilian-felde, 

your changes result in 19 test failures. Please verify your changes and adapt the (supposedly) erroneous tests. 

Thx
Tom

**Comment by maximilian-felde** [comment]
Dear Tom,
I fixed the tests by removing the anonymous-burmeister format from the out-in tests. This format drops the object and attribute names and thus by default fails on these tests -- the exception being contexts that have the standard increasing integer labels for both objects and attributes, because these match the automatically generated labels on context import.

Best regards,
Max

**Comment by exot** [comment]
Hey Max,

I think that before plainly commenting out old test cases because they suddenly fail, it should be properly investigated why the tests fail now and didn't do so before.  IIRC, at least out-in-out-in tests should work even for anonymous-burmeister, shouldn't they?  And anonymous-burmeister always dropped object and attribute names, why is that an issue now?

I would also like to propose to keep this pull request clean: the headline indicates an issue with the definition of the anonymous-burmeister format, but it's not described anywhere what this issue is.  Then, additional commits come into play, talking about resampling, imitating contexts, and Dirichlet contexts – I suppose this has nothing to do with the original issue, does it?  Could you please rebase this PR and include only those commits that are relevant for the issue at hand?  Please also do not include merge commits in your PRs, either use rebasing or rerere (I'm not quite sure that the latter will help, though).

I would also like to encourage you to write more informative commit messages, see https://chris.beams.io/posts/git-commit/ for a good explanation of what that is.  I often wrote bad commit messages myself, but I value good commit messages now that I understood what they are good for :)

Finally, I saw that the "documentation" of the anoymous Burmeister format here: https://github.com/tomhanika/conexp-clj/blob/dev/doc/Common-FCA-File-Formats-for-Formal-Contexts.org is not in par with the actual implementation: the implementation requires to give the number of objects and attributes, whereas the documentation does not say so.  Cloud you also please update the documentation accordingly?

And yes, this documentations needs some love, but that's not the point of this PR ;)

Thanks!

  Daniel

**Comment by maximilian-felde** [comment]
Hey Daniel,

I see how it might have appeared as if I was simply commenting out the failing tests, however I did investigate the reasons to why the tests fail; here is why:

- Before, the tests went through because calling `count` on a context results in an `UnsupportedOperationException` which is caught and accepted (other formats throw this exception, namely :fcalgs, which only accepts integral objects and attributes). 
- Fixing the write part for the :anonymous-burmeister format meant that the tests were actually running.
- The out-in tests fail for the :anonymous-burmeister format basically by design, because the object and attribute labels are discarded.
- The out-in-out-in tests usually fail too because the order of objects and attributes is not guaranteed to be kept intact on write. This is because `(seq (set (range N)))` is not guaranteed to be the same as `(range N)`. Hence the contexts the context after importing is the same context but possibly with shuffled objects and attributes, and thus the equality check fails.


Regarding the pull request itself: 
> Then, additional commits come into play, talking about resampling, imitating contexts, and Dirichlet contexts – I suppose this has nothing to do with the original issue, does it? 
This is correct, I do not know why they were part of the commit tbh; They had no effect on the changes in the pull request. I have now fixed this in my main dev branch and for this pull request.

> Could you please rebase this PR and include only those commits that are relevant for the issue at hand? 
Done. Thanks for the hint on how to do that. I also amended the commit message to better reflect the reasoning behind the changes to the tests.

> Cloud you also please update the documentation accordingly?
Done.

Thank you for the suggestions on how to improve my pull requests in the future :)

Best regards,
Max

**Comment by exot** [comment]
Hey Max,

this looks much better now, thanks!

It's interesting to know that the tests for `:anonymous-burmeister` actually never ran, it's a pity this has only been noticed now.  Does this mean we do not have any tests (and never had) for the `:anonymous-burmeister` format?

I would like to see at least `out-in-out-in` testing work for `:anonymous-burmeister`.  What would be necessary to get there?  I would expected that when reading a formal context in that format that both objects and attributes are simply enumerated from 1 until the actual amount.  The reading order should be determined by the format in the file, and the writing order should be determined by the numbers.  But that wouldn't work if the context to start with does not have sortable objects or attributes … pity again.

Could we instead create a new testing type `out-in-out-in-sorted` or `out-in-out-in-deterministic` that allows to remove the nondeterminism present in the `:anonymous-burmeister` format?  One could sort objects and attributes before every write, if possible.  I am not quite sure whether this would work, though.

Any ideas to test `:anonymous-burmeister`?

Best,

  Daniel

**Comment by mmarx** [comment]
While making the output deterministic is surely something to strive for, an easier fix to get the tests to run would be to just require isomorphic output, not actual equality of the contexts.

**Comment by exot** [comment]
Hey Max,

do we already have isomorphy testing available in `conexp-clj`?  I remember working on this, but I think I never finished it.

For testing, a simple isomorphy test should be enough, though.

Best,

  Daniel

**Comment by maximilian-felde** [comment]
Hey,
 
regarding your comments:

> It's interesting to know that the tests for :anonymous-burmeister actually never ran, it's a pity this has only been noticed now. Does this mean we do not have any tests (and never had) for the :anonymous-burmeister format?

Except the null context out-in-out-in tests, this seems to be the case, yes. 

>  I would expected that when reading a formal context in that format that both objects and attributes are simply enumerated from 1 until the actual amount.

This is indeed the case. The problem is that the writing order is not consistent for numbers due to objects and attributes being stored as sets, e.g., for #{0 1 2 3 4} we get the sequence (0 1 4 3 2).
We could adapt the write function to sort objects and attributes -- the context->string function already does that if I am not mistaken.
Or, we could, as suggested, resort to testing for isomorphy, but:

> do we already have isomorphy testing available in conexp-clj? 

Not as far as I know.
We could easily test for an equal number of objects/attributes/incidences (other invariants?), but truely testing for isomorphy is more complicated.


Best regards,
Max

**Comment by exot** [comment]
Hey Max,

thanks for your feedback!  I would suggest to go the easy way and add some `out-in` (and `out-in-out-in`?) tests for `:anonymous-burmeister` with tests on invariants instead of equality.  Invariants should at least be:
- number of objects stays the same
- number of attributes stays the same
- size of the incidence relation stays the same
- number of concepts stays the same (I am not quite sure whether this is feasible for all our test contexts though)
This way, we can be sure that IO for the `:anoymous-burmeister` format is working in some plausible way, which is better than nothing.

What do you think?  If this is okay for you, could you implement this?

Thanks,

  Daniel

**Comment by maximilian-felde** [comment]
Hey Daniel,

sounds good, I will implement some tests for the `:anonymous-burmeister`. Regarding the computation of the number of concepts: I will make sure to only use relatively small contexts.

Best regards,
Max

**Review by exot — APPROVED** [review]
Hey Max,

sorry for my late reply.  I have checked your pull request and looks good to me, thanks!

NB: when running the tests, I get this strange warning:

```
$ lein test conexp.io.contexts-test
Initializing NoDisassemble Transformer

lein test conexp.io.contexts-test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by clojure.lang.InjectedInvoker/0x0000000840095c40 (file:/home/exot/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar) to method com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(java.io.Reader)
WARNING: Please consider reporting this to the maintainers of clojure.lang.InjectedInvoker/0x0000000840095c40
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Ran 9 tests containing 359 assertions.
0 failures, 0 errors.
```

Do you have any clue where this is coming from?

@tomhanika: could you please make sure the documentation for the anonymous Burmeister format is updated as well?

Thanks!

  Daniel

**Pull request merged**
