### PR TITLE
Added grid field to GUI

### PR DESCRIPTION
**Pull request by De-Narm**
Added a new field to discretize layouts (as requested by Dominik).
Upon using the dimdraw button "Exact" the grid value is updated.

### CODE REVIEW

**Comment by hirthjo** [comment]
The implemented function works nicely with dimdraw. 

- Please add function to estimate a good grid size for arbitrary drawings (trade off between small and accurate). Maybe as function that determines the best grid for a given parameter range as input?
- (If not to much effort) Make grid displayable by small black points

**Comment by De-Narm** [comment]
@hirthjo 
As of now the grid is drawable by toggle and there's a rough estimation for each new lattice drawn.

The estimation simply takes the number of distinct position values for each dimension. I've experimented with smaller estimations based on dropping points from pairs with a small distance between them (e.g. below quarter of the average distance between sorted x-values) but certain cases always break them (e.g. force drawings). This could be fixed by giving the user a lot more options but those would clutter the interface.
Any other ideas to approach this or does the rough estimate suffice for the user to manually chose a smaller matching size?

**Comment by hirthjo** [comment]
Thanks again for your valuable contribution.

Here some smaller requests:
- Add "Fit Grid" Button rather then pressing enter in the checkbox
- Rename "Grid" Button to "Toggle Grid"
- Update Grid view when changing grid size
- Create Button to call the grid suggestion for the current layout

Bugs(?):
- After fitting a random drawing to the grid the coordinates are not discrete in the tikz export
- The initial Grid plot does not seem to be accurate. I drew the concept lattice of a boolean 4x4 context, moved some points and after refitting the points to the grid there were some points off the plotted grid.

**Comment by De-Narm** [comment]
@hirthjo 
Greetings,

* I added the buttons you wanted, but I couldn't rename the toggle button due to limitations in how the GUI is designed. The actual button text is used to determine the current state of the grid (see also the "Label/No Label" button)
* The grid is now properly updated when needed.

Bugs(?):
* The "discretize"-function already in the code only moves points within the boundaries of the prior man/min value of each dimension (e.g between 0 and 1).
* The second bug should be fixed with the grid now updating properly, at least I couldn't reproduce it.

**Comment by hirthjo** [comment]
Thank your for your fast response and contribution.
Requests:
- Rename "Grid Button" to "toggle"
- Give the "Estima.." a shorter name
- Let the grid have discrete coordinates only
- Merge default into your branch

**Comment by hirthjo** [comment]
- When pressing the "Estimate" button update the grid view

**Comment by De-Narm** [comment]
@hirthjo 
I added all that was requested, note that:
* As explained earlier, I need two different names for the button to actual work. As per your request I chose "Toggle On" and "Toggle Off".
* I added a new function on top of the old discretize function to use discrete values to avoid breaking any other functions who may depend on the old output.

**Comment by hirthjo** [comment]
Thank you for your update
- The name "Toggle on" is to long for the button. Please name it "Toggle" instead
- Using the "Fit Grid" and "Auto Grid" button causes an error if the "Toggle" button was not pressed before

**Comment by De-Narm** [comment]
@hirthjo 
The bug should be fixed.

**Comment by hirthjo** [comment]
Thank you for your fix.
The Fit Grid button does not seem to be idempotent. When using the DimDraw Layout every point is aligned nicely to the grid. Repetitive pressing of the Fit Grid button however causes already aligned points to jump to other points until it converged to a single point. Please investigate if there is a bug causing this. Otherwise, please change the fit grid operation such that it does not reassign fitted points to other grid coordinates.

**Comment by De-Narm** [comment]
@hirthjo 
I messed up the rounding last time but now it works as intended.

**Comment by hirthjo** [comment]
Thank you for your contribution. Everything works nicely now.
Please merge the current default into your branch and check if the project builds successfully.

**Comment by De-Narm** [comment]
Ah, sorry, I must have overwritten the last merge I did.
Everything compiles with all profiles.

**Pull request merged**
