### PR TITLE
ms/k-cores

### PR DESCRIPTION
**Pull request by mstubbemann**
Hey Daniel,
I implemented the functionality to compute the k-cores:
The k-cores of a graph g are the connected components of the maximal subgraph of g
in which every node has at least k edges.

To compute the connected components, I implemented the breadth-first-search in a way, that for a node n and a graph g a map is returned that has the reachable nodes as keys and the distances to n as values. The idea behind storing the distances is to use the bfs also as an alternative way to compute the average-shortest-path-lengths.

Regards,
Max

### CODE REVIEW

**Comment by exot** [comment]
Hey Max,

thanks for this pull request.  I will have a look at it as soon as possible (which, however, may not be soon, because I am currently quite busy …)

Cheers,

  Daniel

**Comment by exot** [comment]
Hey Max,

I finally found some time to look into your pull request.  It looks good to me, and I have made only very little modifications to your changes.  These are stored in `ms/k-cores`, and if you are fine with these, please pull them in your pull request and give me a short notification here, so I can merge this pull request into `dev`.

Cheers,

  Daniel

**Comment by exot** [comment]
Another thing that just came to my mind: from a software engineering point of view, I think it would be better to refactor the graph code contained in your implementation on socialanalysis and provide it in more generality in conexp-clj.  A first guess would be to put it under `conexp.math.graphs` or somesuch.  What do you think?  In any way, this refactoring should not be part of this PR, and I would open a separate issue for it.

**Comment by Kama93** [comment]
Hey Daniel,

I am fine with your modifications and added them to the PR.

As I continued adding more functionality to socialanalytics in the last months, the code got longer and longer and I also thought about separating the code that is more about graph structure then social analytics from the code that deals with typical network analysis measures.

My approach was to convert **fca/applications/socialanalytics.clj** to **fca/applications/networks/socialanalytics.cj** and **fca/applications/networks/structure.clj**, but I guess the idea is basicially the same as yours (modulo moving and renaming  structure.clj). You can have a look at it in my branch ms/SNA-WS-18-19 and tell me if that is close to what you were thinking about.

So yes, I definitly support your idea about moving the code about basic graph structure and algorithms into a different file.

Cheers,

Max

**Comment by mstubbemann** [comment]
Closed in favor of #29.

**Pull request closed without merging**
